### ISSUE TITLE
Install fails with node v16.13.1 and npm v8.3.0

### ISSUE THREAD

**Issue by mlewus** [jc21/MMM-PiLights#11]
I just tried to install this on a new install of Magic Mirror. I am using the recommended node npm v16.13.1 and npm 8.3.0. It fails at npm install. Here is the output:

pi@magic-mirror:~/MagicMirror/modules/MMM-PiLights $ npm install

> MMM-PiLights@1.1.0 postinstall
> node_modules/.bin/electron-rebuild -e ../../node_modules/electron

⠋ Searching dependency tree
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 13.5.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 13.5.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/MagicMirror/modules/MMM-PiLights/node_modules/node-abi/index.js:30:9)
    at new Rebuilder (/home/pi/MagicMirror/modules/MMM-PiLights/node_modules/electron-rebuild/lib/src/rebuild.js:122:28)
    at rebuildWithOptions (/home/pi/MagicMirror/modules/MMM-PiLights/node_modules/electron-rebuild/lib/src/rebuild.js:393:23)
    at Object.doRebuild [as rebuild] (/home/pi/MagicMirror/modules/MMM-PiLights/node_modules/electron-rebuild/lib/src/rebuild.js:400:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-PiLights/node_modules/electron-rebuild/lib/src/cli.js:115:33)
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/MagicMirror/modules/MMM-PiLights/node_modules/electron-rebuild/lib/src/cli.js:5:58)
npm ERR! code 255
npm ERR! path /home/pi/MagicMirror/modules/MMM-PiLights
npm ERR! command failed
npm ERR! command sh -c node_modules/.bin/electron-rebuild -e ../../node_modules/electron

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-12-30T19_56_49_131Z-debug-0.log
pi@magic-mirror:~/MagicMirror/modules/MMM-PiLights $

Any idea how to proceed?
Thanks

**Comment by robertalexa** [comment]
Same here.

As a result, I have rm -rf node_modules and ran npm install from fresh basically.

That now brings a new set of errors.
```
Building module: spi-device, Completed: 1In file included from /home/pi/.electron-gyp/16.0.5/include/node/v8-local-handle.h:12,
                 from /home/pi/.electron-gyp/16.0.5/include/node/v8-array-buffer.h:12,
                 from /home/pi/.electron-gyp/16.0.5/include/node/v8.h:25,
                 from /home/pi/.electron-gyp/16.0.5/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/spi.cc:2:
/home/pi/.electron-gyp/16.0.5/include/node/v8-internal.h:113:27: error: static assertion failed: Pointer compression can be enabled only for 64-bit architectures
     kApiSystemPointerSize == kApiInt64Size,
     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/home/pi/.electron-gyp/16.0.5/include/node/v8-internal.h:471:71: warning: left shift count >= width of type [-Wshift-count-overflow]
   static constexpr size_t kPtrComprCageReservationSize = size_t{1} << 32;
                                                                       ^~
/home/pi/.electron-gyp/16.0.5/include/node/v8-internal.h:471:68: error: right operand of shift expression ‘(1 << 32)’ is >= than the precision of the left operand [-fpermissive]
   static constexpr size_t kPtrComprCageReservationSize = size_t{1} << 32;
                                                          ~~~~~~~~~~^~~~~
/home/pi/.electron-gyp/16.0.5/include/node/v8-internal.h:472:69: warning: left shift count >= width of type [-Wshift-count-overflow]
   static constexpr size_t kPtrComprCageBaseAlignment = size_t{1} << 32;
                                                                     ^~
/home/pi/.electron-gyp/16.0.5/include/node/v8-internal.h:472:66: error: right operand of shift expression ‘(1 << 32)’ is >= than the precision of the left operand [-fpermissive]
   static constexpr size_t kPtrComprCageBaseAlignment = size_t{1} << 32;
                                                        ~~~~~~~~~~^~~~~
⠧ Building module: spi-device, Completed: 1In file included from ../../nan/nan.h:2884,
                 from ../src/spi.cc:2:
../../nan/nan_typedarray_contents.h: In constructor ‘Nan::TypedArrayContents<T>::TypedArrayContents(v8::Local<v8::Value>)’:
../../nan/nan_typedarray_contents.h:34:43: error: ‘class v8::ArrayBuffer’ has no member named ‘GetContents’; did you mean ‘IsContext’?
       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                           ^~~~~~~~~~~
                                           IsContext
⠋ Building module: spi-device, Completed: 1make: *** [spi.target.mk:131: Release/obj.target/spi/src/spi.o] Error 1
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-PiLights/node_modules/spi-device/build'
✖ Rebuild Failed

```

@jc21 Is this still something that you use and look after?

**Comment by mlewus** [comment]
I think I found the root cause of the problem, unfortunately I don’t know how to fix it. I ran
`npm install --save-dev electron-rebuild`
as recommended on the initial npm install then re-ran 
` npm install `
This allowed me to see the underlying compile errors. It is failing in the makefile ~/MagicMirror/modules/MMM-PiLights/node_modules/spi-device/binding.gyp while compiling 
spi-device. 

I previously ran MMM-PiLights successfully on the 4.19.x kernel and recently upgraded with:
`sudo apt update`
`sudo apt upgrade`
and installed the latest MagicMirror version from scratch. I am now running Buster with kernel 5.10.63-v7l+ #1496 SMP and gcc version 7.3.0 (Raspbian 7.3.0-19).

Here is the output:

⠋ Building module: spi-device, Completed: 1In file included from ../../nan/nan.h:2884,
                 from ../src/spi.cc:2:
../../nan/nan_typedarray_contents.h: In constructor ‘Nan::TypedArrayContents<T>::TypedArrayContents(v8::Local<v8::Value>)’:
../../nan/nan_typedarray_contents.h:34:43: error: ‘class v8::ArrayBuffer’ has no member named ‘GetContents’; did you mean ‘IsContext’?
       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
…………………………………………………..^~~~~~~~~~~
……………………………………………………IsContext
⠴ Building module: spi-device, Completed: 1make: *** [spi.target.mk:121: Release/obj.target/spi/src/spi.o] Error 1
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-PiLights/node_modules/spi-device/build'
✖ Rebuild Failed

Any help with this would be greatly appreciated.
Thanks

**Comment by robertalexa** [comment]
FYI
https://forum.magicmirror.builders/topic/16074/electron-rebuild-and-magicmirror-v2-18-and-more

I will try to find some time and dig further.

**Comment by mlewus** [comment]
@robertalexa, thanks for looking at this. I poked around a bit and found that lpd8806-async depends on spi-device, and spi-device depends on nan. The versions of spi-device and nan are both too old to work with node v16. spi-device is v2.0.8 and nan is v2.14, The current versions are 3.1.12 and 2.15, respectively. 

These are referenced in package_lock.json:
lpd8806-async @ line 812
spi-device @ line 871, 1320, 1400
nan @ line 1406

I understand package_lock.json is an auto generated file. I don't know enough about node programming to fix it, but I'm posting this in hope it will be of some assistance.

**Comment by robertalexa** [comment]
What i can suggest in the meantime, while i try and figure sth out, make a backup of your current node_modules folder and package-lock.json. Then delete them and run npm install. This should run from fresh, and should include newer version packages.

For me the error is even weirder.

**Comment by robertalexa** [comment]
@mlewus Are you using lpd or ws2801?

I think long story short is that the packages are all old. I am not profficient in nodejs either, so I have limited knowledge on the topic, but i will see if i can get this to work for my use case

**Comment by mlewus** [comment]
I’m using lpd.

**Comment by robertalexa** [comment]
I have removed the lpd dependency as that is not needed in my case, and I have forked the ws dependency and updated spi-device to latest 3.1.2.

Electron rebuild still fails in the same place

**Comment by mlewus** [comment]
Both WS and LPD depend on spi-device, and spi-device depends on nan. Did you update that as well? On the nan page they said v2.14 is not compatible with newer versions of node.

**Comment by mlewus** [comment]
Solved.
Install PiLights with:
`cd ~/MagicMirror/modules`
`git clone https://github.com/jc21/MMM-PiLights.git`
`cd MMM-PiLights`
`npm install --save-dev electron-rebuild`
`npm update nan`
`npm update spi-device`
`npm install`
Mine works now. @robertalexa, let me know if it works for you and if so I’ll close this.

**Comment by robertalexa** [comment]
Same error for me.
![image](https://user-images.githubusercontent.com/9019306/147886897-52100dd2-874c-4cfc-8892-45eb8932362d.png)

As mentioned before, I have not struggled with the version per say, but rather failing assertions in rebuild. But might still be because of outdated packages

**Comment by mlewus** [comment]
What version of node and npm are you using?

**Comment by robertalexa** [comment]
Node 16.13.1
npm 6.14.15

Can't update npm to latest as the MMM-GoogleAssistant module is not working with npm 7

**Comment by mlewus** [comment]
I'm running node 16.13.1 and npm 8.3.0 and it's working now. I don't know enough about the interaction between node and npm versions to make an intelligent comment about your configuration. 

You might try this - if you search on the nan and spi-device packages on https://www.npmjs.com you can see all past versions, updates made, and the versions of node they support. Once PiLights installs and fails you can install past versions of nan and spi-device with
`npm install package@version`
then
`npm install` 
from the MMM-PiLights directory. There might be some combination of package versions that will work.

I read somewhere that the initial clean install of PiLights should be done with 
`npm install --save-dev electron-rebuild` instead of
`npm install`
You can read about using it at https://github.com/electron/electron-rebuild

I have a background with C/C++ but I've never programmed in js or node. So take this all of the huge grain of salt.

**Comment by robertalexa** [comment]
Ok, so through trial and error i have managed to get it to work.

In short:
- spi-device needs to update their dependency on nan to 2.15.0
- LPD8806-node and node-rpi-ws2801 to update their dependency on spi-device to 3.1.5

But personally i don't know if this will happen.

I also ended up using bugsonet's package magicmirror-rebuild which i have posted in a comment above.

**Comment by mlewus** [comment]
Yes, from my Jan 2 post:
`npm update nan`
`npm update spi-device`
updates to those versions. 

I think we can assume this is an abandoned project as it has not been updated in a long time. I'm just glad its creator left the code here on Github for us to use. With so many node libraries and few if any paid maintainers, I suspect this is a common type of problem with node apps.

I guess I'm going to have to get more proficient with node if I want to keep updating my Mirror. Glad you got yours working.

**Comment by mlewus** [comment]
I did more research on this and the problem is not in this package. It’s in the LPD8806-node package at https://github.com/Trekky12/LPD8806-node
The dependencies for nan and spi-device just need to be updated. I’m going to open an issue there, hopefully he is still maintaining that code.
